version: '3'
services:
  my-app:
    build: .
    ports:
    - "80:80"

  db:
    image: "postgres:11"
    container_name: "postgres_database"
    environment:
      - POSTGRES_PASSWORD=rightspotpassword
      - POSTGRES_USER=admin_rightspot
      - POSTGRES_DB=rightspot
    ports:
      - "5432:5432" # If you want to expose the db from the container
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: {}